# Generated by Django 3.0.6 on 2020-06-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_admins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
