# Generated by Django 3.0.6 on 2020-09-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mail', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[['active', 'ACTIVE'], ['deleted', 'DELETED']], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='/imgs/user_placeholder.png', upload_to='imgs/')),
                ('name', models.CharField(max_length=250)),
                ('roles', models.TextField(blank=True, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_edited_by', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField()),
                ('venue', models.TextField()),
                ('creator', models.CharField(max_length=250)),
                ('audience', models.TextField()),
                ('state', models.CharField(choices=[['created', 'CREATED'], ['approved', 'APPROVED'], ['published', 'PUBLISHED'], ['scheduled', 'SCHEDULED'], ['completed', 'COMPLETED'], ['deleted', 'DELETED']], default='created', max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
            ],
        ),
    ]
