# Generated by Django 3.0.6 on 2020-09-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='roles',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Coordinator', max_length=250)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Coordinator')),
            ],
        ),
    ]
