# Generated by Django 3.0.6 on 2020-09-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20200928_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='roles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
