# Generated by Django 3.0.6 on 2020-09-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20200928_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinator',
            new_name='Member',
        ),
    ]
