# Generated by Django 3.0.6 on 2020-09-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_clubmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='/imgs/user_placeholder.png', upload_to='imgs/')),
                ('name', models.CharField(max_length=250)),
                ('roles', models.TextField(blank=True, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='img',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='roles',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='Coordinator', max_length=250),
        ),
        migrations.DeleteModel(
            name='ClubMembership',
        ),
    ]
