# Generated by Django 3.0.6 on 2020-09-28 21:31

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20200928_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active_year',
            field=models.IntegerField(default=clubs.models.current_year),
        ),
    ]
