# Generated by Django 3.0.7 on 2020-11-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_auto_20200928_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
