# Generated by Django 3.0.7 on 2020-11-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_event_financial_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.TextField(default='-'),
        ),
    ]
