# Generated by Django 3.0.7 on 2020-11-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20201102_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(default='1 hr', max_length=100),
        ),
    ]
