# Generated by Django 3.0.7 on 2021-01-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_auto_20201103_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='img',
            field=models.ImageField(blank=True, default='/imgs/clubs/club_placeholder.jpg', upload_to='imgs/clubs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='/imgs/users/user_placeholder.png', upload_to='imgs/users/'),
        ),
    ]
