# Generated by Django 3.0.6 on 2020-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.TextField()),
                ('audience', models.CharField(choices=[['none', '-'], ['ug1', 'UG 1'], ['ug2', 'UG 2'], ['ug3', 'UG 3'], ['ug4', 'UG 4']], default='none', max_length=100)),
                ('state', models.CharField(choices=[['created', 'CREATED'], ['approved', 'APPROVED'], ['published', 'PUBLISHED'], ['scheduled', 'SCHEDULED']], default='created', max_length=50)),
            ],
        ),
    ]
