# Generated by Django 3.0.6 on 2020-05-28 21:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('club', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.TextField()),
                ('created_by', models.CharField(max_length=250)),
                ('audience', multiselectfield.db.fields.MultiSelectField(choices=[['none', '-'], ['ug1', 'UG 1'], ['ug2', 'UG 2'], ['ug3', 'UG 3'], ['ugx', 'UG 4+'], ['pg', 'PG'], ['staff', 'Staff'], ['faculty', 'Faculty']], max_length=37)),
                ('state', models.CharField(choices=[['created', 'CREATED'], ['approved', 'APPROVED'], ['published', 'PUBLISHED'], ['scheduled', 'SCHEDULED']], max_length=50)),
            ],
        ),
    ]
