# Generated by Django 3.0.6 on 2020-06-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='club',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[['created', 'CREATED'], ['approved', 'APPROVED'], ['published', 'PUBLISHED'], ['scheduled', 'SCHEDULED'], ['completed', 'COMPLETED'], ['deleted', 'DELETED']], max_length=50),
        ),
    ]
