# Generated by Django 3.0.6 on 2020-06-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200601_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TextField(),
        ),
    ]
