# Generated by Django 3.0.6 on 2020-06-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_event_audience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
