# Generated by Django 3.0.6 on 2020-06-02 20:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200602_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=multiselectfield.db.fields.MultiSelectField(choices=[['none', '-'], ['ug1', 'UG 1'], ['ug2', 'UG 2'], ['ug3', 'UG 3'], ['ugx', 'UG 4+'], ['pg', 'PG'], ['staff', 'Staff'], ['faculty', 'Faculty']], default='none', max_length=37),
            preserve_default=False,
        ),
    ]
