# Generated by Django 3.0.6 on 2020-06-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_event_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.TextField(),
        ),
    ]
