# Generated by Django 3.0.6 on 2020-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_coordinator_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='clubs',
            field=models.ManyToManyField(to='base.Club'),
        ),
    ]
