# Generated by Django 3.0.6 on 2020-06-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_coordinator_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='clubs',
        ),
        migrations.AddField(
            model_name='club',
            name='coordinators',
            field=models.ManyToManyField(to='base.Coordinator'),
        ),
    ]
