# Generated by Django 3.0.6 on 2020-06-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200608_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='role',
            field=models.CharField(default='Coordinator', max_length=250),
        ),
    ]
