# Generated by Django 3.0.6 on 2020-06-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_coordinator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='state',
            field=models.CharField(choices=[['active', 'ACTIVE'], ['deleted', 'DELETED']], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[['created', 'CREATED'], ['approved', 'APPROVED'], ['published', 'PUBLISHED'], ['scheduled', 'SCHEDULED'], ['completed', 'COMPLETED'], ['deleted', 'DELETED']], default='created', max_length=50),
        ),
    ]
