# Generated by Django 3.0.6 on 2020-07-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20200710_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='roles',
            field=models.TextField(default='1$COordinator'),
            preserve_default=False,
        ),
    ]
