# Generated by Django 3.0.6 on 2020-07-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_coordinator_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='role',
        ),
    ]
