# Generated by Django 3.0.6 on 2020-08-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_coordinator_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='roles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
