# Generated by Django 3.0.6 on 2020-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_club_coordinators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
