# Generated by Django 3.0.6 on 2020-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200801_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='img',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
    ]
