# Generated by Django 3.0.6 on 2020-08-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20200801_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='img',
            field=models.ImageField(blank=True, default='/media/imgs/user_placeholder.png', upload_to='imgs/'),
        ),
    ]
