# Generated by Django 3.0.6 on 2020-08-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20200801_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='img',
            field=models.ImageField(blank=True, default='/imgs/user_placeholder.png', upload_to='imgs/'),
        ),
    ]
