# Generated by Django 3.0.6 on 2020-08-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20200803_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
