# Generated by Django 3.0.6 on 2020-08-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20200812_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
    ]
