# Generated by Django 3.0.6 on 2020-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(default='1 hour', max_length=100),
            preserve_default=False,
        ),
    ]
