# Generated by Django 3.0.6 on 2020-08-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetproposal',
            name='datetime',
        ),
    ]
